import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { ServerConfig } from "../../config.js";
import { runCli, formatResult } from "../../cli_runner.js";

export function register(server: McpServer, config: ServerConfig) {
  server.tool(
    "jui_sync_tool",
    "Sync the project's platform-local tool checkouts (sjui_tools / kjui_tools / rjui_tools under each platform root) with the home install (~/.jsonui-cli/ or $JSONUI_CLI_PATH). Preserves every `extensions/` directory — that's where custom converters generated by `rjui g converter` etc. live. Also propagates each tool's `.ruby-version` to the platform root so that standalone `rjui build` (not routed through `jui build`) picks up the correct Ruby via rbenv. Safe to run after bumping jsonui-cli or when bootstrapping a newly scaffolded platform (target dir is created on first run).",
    {
      platform: z.enum(["ios", "android", "web"]).optional().describe("Sync only one platform. Defaults to every platform listed in jui.config.json."),
      prune: z.boolean().optional().describe("Delete files in the target that don't exist in the source (never inside extensions/). Default false."),
      dry_run: z.boolean().optional().describe("Show what would change without writing any files."),
      from: z.string().optional().describe("Override source CLI root (default: $JSONUI_CLI_PATH or ~/.jsonui-cli/)."),
      project_dir: z.string().optional().describe("Project directory (overrides JUI_PROJECT_DIR env)"),
    },
    async (params) => {
      try {
        const projectDir = config.resolveProjectDir(params.project_dir);
        const args = ["sync_tool"];
        if (params.platform) { args.push("--platform", params.platform); }
        if (params.prune) { args.push("--prune"); }
        if (params.dry_run) { args.push("--dry-run"); }
        if (params.from) { args.push("--from", params.from); }

        const result = await runCli("jui", args, { cwd: projectDir });
        return { content: [{ type: "text", text: formatResult(result) }] };
      } catch (e: any) {
        return { content: [{ type: "text", text: `Error: ${e.message}` }] };
      }
    }
  );
}
